### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Maestro-Zacht** [Maestro-Zacht/allianceauth-pve#11]
- [x] Default priority to 100
- [x] explanation under custom increment
- [x] fix search
- [x] copy-paste to closed rotation
- [x] comma separators in inputs
- [x] only mains in search
- [x] fix issue with zero division in totals
- [x] add tests for only mains in search
- [x] add tests for search alt
- [x] add alt list in search
